apiVersion: apps/v1
kind: Deployment
metadata:
 name: devdeploy
 labels:
  name: devdeploy
spec:
 replicas: 2
 selector:
  matchLabels:
   name: devpod
 template:
  metadata:
   name: devpod
   labels:
    name: devpod
  spec:
   containers:
   - name: devcontainer
     image: stackupiss/dov-bear:v2
     imagePullPolicy: IfNotPresent
     ports:
     - containerPort: 3000
     env:
     - name: INSTANCE_NAME
       valueFrom:
        secretKeyRef:
         name: devsecret
         key: INSTANCE_NAME
     - name: INSTANCE_HASH
       valueFrom:
        secretKeyRef:
         name: devsecret
         key: INSTANCE_HASH