apiVersion: v1
kind: Pod
metadata:
 name: devpod
 labels:
  name: devpod
  version: v1
spec:
 containers:
 - name: devcontainer
   image: stackupiss/dov-bear:v2
   imagePullPolicy: IfNotPresent
   ports:
   - containerPort: 3000
~                         