apiVersion: v1
kind: Pod
metadata:
 name: devpod
 labels:
  name: devpod
  version: v1
spec:
 containers:
 - name: container
   image: stackupiss/bgg-database:v1
   imagePullPolicy: IfNotPresent
   ports:
   - containerPort: 3307