apiVersion: apps/v1
kind: Deployment
metadata:
 name: devdeploy
 labels:
  name: devdeploy
spec:
 replicas: 3
 selector:
  matchLabels:
   name: bggapp
 template:
  metadata:
   name: bggapp
   labels:
    name: bggapp
  spec:
   containers:
   - name: container
     image: stackupiss/bgg-backend:v1
     imagePullPolicy: IfNotPresent
     ports:
     - containerPort: 3000
    env:
      - name: BGG_DB_USER
        valueFrom:
         configMapKeyRef:
          name: devconfig
          key: bgg_db_user
      - name: BGG_DB_HOST
        value: devservice
      - name: BGG_DB_PASSWORD
        valueFrom:
         secretKeyRef:
          name: devsecret
          key: bgg_db_password